#!/bin/bash

# Check for template files and process them

templates(){
    if [ -d "$TEMPLATE_DIR" ]; then
        for template in "$TEMPLATE_DIR"/*; do
            template_name=$(basename "$template")
            output_template="$OUTPUT_DIR/$template_name"

            # Replace placeholders in the template
            sed \
                -e "s/{background}/$background/g" \
                -e "s/{foreground}/$foreground/g" \
                -e "s/{cursor}/$cursor/g" \
                -e "s/{color0}/$color0/g" \
                -e "s/{color1}/$color1/g" \
                -e "s/{color2}/$color2/g" \
                -e "s/{color3}/$color3/g" \
                -e "s/{color4}/$color4/g" \
                -e "s/{color5}/$color5/g" \
                -e "s/{color6}/$color6/g" \
                -e "s/{color7}/$color7/g" \
                -e "s/{color8}/$color8/g" \
                -e "s/{color9}/$color9/g" \
                -e "s/{color10}/$color10/g" \
                -e "s/{color11}/$color11/g" \
                -e "s/{color12}/$color12/g" \
                -e "s/{color13}/$color13/g" \
                -e "s/{color14}/$color14/g" \
                -e "s/{color15}/$color15/g" \
                "$template" > "$output_template"

            echo "[*] Processed template $template_name saved in $OUTPUT_DIR"
        done
    else
        echo "[ ] No templates found in $TEMPLATE_DIR"
    fi
}
