#!/bin/bash

# Important variables.
IMAGE_PATH="$1"
THEME=0 # 0 = dark, 1 = light
OUTPUT_DIR="$HOME/.cache/shwal"
TEMPLATE_DIR="$HOME/.config/shwal/templates"
SCRIPT_DIR="$HOME/.config/shwal/scripts"
mkdir -p "$OUTPUT_DIR"
MAX_ATTEMPTS=10
attempt=1
resize=25
colors=()

